/*
 StackMob JS SDK Version 0.6.0
 Copyright 2012 StackMob Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

(function(){window.StackMob=this.StackMob={DEFAULT_API_VERSION:0,DEFAULT_LOGIN_SCHEMA:"user",DEFAULT_LOGIN_FIELD:"username",DEFAULT_PASSWORD_FIELD:"password",EARTH_RADIANS_MI:3956.6,EARTH_RADIANS_KM:6367.5,FORCE_CREATE_REQUEST:"stackmob_force_create_request",ARRAY_FIELDNAME:"stackmob_array_fieldname",ARRAY_VALUES:"stackmob_array_values",CASCADE_DELETE:"stackmob_cascade_delete",HARD_DELETE:!0,SOFT_DELETE:!1,API_SERVER:"api.stackmob.com",RETRY_WAIT:1E4,RETRY_ATTEMPTS:3,REFRESH_TOKEN_KEY:"oauth2.refreshToken",
POST:"POST",PUT:"PUT",DELETE:"DELETE",CONTENT_TYPE_JSON:"application/json",apiVersion:0,sdkVersion:"0.6.0",publicKey:null,Storage:{STORAGE_PREFIX:"stackmob.",persist:function(d,f){localStorage&&localStorage.setItem(this.STORAGE_PREFIX+d,f)},retrieve:function(d){return localStorage?localStorage.getItem(this.STORAGE_PREFIX+d):null},remove:function(d){localStorage&&localStorage.removeItem(this.STORAGE_PREFIX+d)}},getLoggedInUser:function(){var d=!this.isOAuth2Mode()&&this.Storage.retrieve(this.loggedInUserKey)||
this.Storage.retrieve("oauth2.user");return this.isLoggedIn()&&d?d:null},isLoggedIn:function(){return!this.isLoggedOut()||this.hasValidOAuth()},isUserLoggedIn:function(d){return d==this.getLoggedInUser()},isLoggedOut:function(){return!this.hasValidOAuth()},getScheme:function(){return!0===this.secure?"https":"http"},getDevAPIBase:function(){return"undefined"!==typeof PhoneGap?this.getScheme()+"://"+StackMob.API_SERVER+"/":!0===this.fullURL?this.getScheme()+"://dev."+this.appName+"."+this.clientSubdomain+
".stackmobapp.com/":"/"},getProdAPIBase:function(){return"undefined"!==typeof PhoneGap?this.getScheme()+"://"+StackMob.API_SERVER+"/":!0===this.fullURL?this.getScheme()+"://"+this.appName+"."+this.clientSubdomain+".stackmobapp.com/":"/"},getBaseURL:function(){return StackMob.apiURL||(StackMob.fullURL?0===StackMob.apiVersion?StackMob.getDevAPIBase():StackMob.getProdAPIBase():window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:"")+"/")},throwError:function(d){throw Error(d);
},urlError:function(){this.throwError('A "url" property or function must be specified')},requirePublicKey:function(){StackMob.publicKey||this.throwError("Error: This requires that you initialize StackMob with a public key.")},isOAuth2Mode:function(){return!isNaN(StackMob.publicKey&&!StackMob.privateKey)},prepareCredsForSaving:function(d,f,a,b,c){b=(new Date).getTime()+1E3*b;d={"oauth2.accessToken":d,"oauth2.macKey":a,"oauth2.expires":b,"oauth2.user":c};d[StackMob.REFRESH_TOKEN_KEY]=f;return d},saveOAuthCredentials:function(d){var f=
d["oauth2.accessToken"],a=d[StackMob.REFRESH_TOKEN_KEY];this.Storage.retrieve("oauth2.accessToken")!=f&&this.Storage.persist("oauth2.expires",d["oauth2.expires"]);this.Storage.persist("oauth2.accessToken",f);this.Storage.persist(StackMob.REFRESH_TOKEN_KEY,a);this.Storage.persist("oauth2.macKey",d["oauth2.macKey"]);this.Storage.persist("oauth2.user",d["oauth2.user"])},hasValidOAuth:function(){if(!this.isOAuth2Mode())return!1;var d=this.getOAuthCredentials(),f=d["oauth2.expires"]||0;return _.all([d["oauth2.accessToken"],
d["oauth2.macKey"],f],_.identity)&&(new Date).getTime()<=f},shouldSendRefreshToken:function(){return this.hasExpiredOAuth()&&this.hasRefreshToken()&&this.shouldKeepLoggedIn()},keepLoggedIn:function(d){StackMob.Storage.persist("oauth2.shouldKeepLoggedIn",!0===d)},shouldKeepLoggedIn:function(){return"true"===StackMob.Storage.retrieve("oauth2.shouldKeepLoggedIn")},hasRefreshToken:function(){var d=this.getOAuthCredentials();return d&&"undefined"!==typeof d[StackMob.REFRESH_TOKEN_KEY]&&null!=d[StackMob.REFRESH_TOKEN_KEY]},
getRefreshToken:function(){return this.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY]},hasExpiredOAuth:function(){return this.isOAuth2Mode()&&null==this.getOAuthExpireTime()||this.getOAuthExpireTime()<=(new Date).getTime()},getOAuthCredentials:function(){var d=StackMob.Storage.retrieve("oauth2.accessToken"),f=StackMob.Storage.retrieve("oauth2.macKey"),a=StackMob.Storage.retrieve("oauth2.expires"),b=StackMob.Storage.retrieve(StackMob.REFRESH_TOKEN_KEY),d={"oauth2.accessToken":d,"oauth2.macKey":f,
"oauth2.expires":a};d[StackMob.REFRESH_TOKEN_KEY]=b;return d},getOAuthExpireTime:function(){var d=this.Storage.retrieve("oauth2.expires");return d?parseInt(d):null},METHOD_MAP:{create:"POST",read:"GET",update:"PUT","delete":"DELETE",post:"POST",get:"GET",put:"PUT",addRelationship:"POST",appendAndSave:"PUT",deleteAndSave:"DELETE",login:"GET",accessToken:"POST",refreshToken:"POST",logout:"GET",forgotPassword:"POST",loginWithTempAndSetNewPassword:"GET",resetPassword:"POST",facebookAccessToken:"POST",
createUserWithFacebook:"GET",linkUserWithFacebook:"GET",cc:"GET"},getProperty:function(d,f){return!d||!d[f]?null:_.isFunction(d[f])?d[f]():d[f]},init:function(d){d=d||{};this.initStart(d);this.userSchema=d.userSchema||this.DEFAULT_LOGIN_SCHEMA;this.loginField=d.loginField||this.DEFAULT_LOGIN_FIELD;this.passwordField=d.passwordField||this.DEFAULT_PASSWORD_FIELD;this.newPasswordField=d.newPasswordField||"new_password";this.apiVersion=d.apiVersion||this.DEFAULT_API_VERSION;this.appName=this.getProperty(d,
"appName")||this.throwError("An appName must be specified");this.clientSubdomain=this.getProperty(d,"clientSubdomain");this.publicKey=d.publicKey;this.apiURL=d.apiURL;this.oauth2targetdomain=d.oauth2targetdomain||this.oauth2targetdomain||"www.stackmob.com";this.secure=!0===d.secure;this.fullURL=!0===d.fullURL||"undefined"!==typeof PhoneGap||this.fullURL;this.ajax=d.ajax||this.ajax;this.debug=0===this.apiVersion;this.urlRoot=d.urlRoot||this.getBaseURL();this.initEnd(d);return this},initStart:function(){},
initEnd:function(){}}}).call(this);
(function(){function d(a,b){var c=StackMob.getBaseURL(),l=b.url.replace(RegExp(c,"g"),"/"),g=c.replace(RegExp("^http://|^https://","g"),"").replace(/\//,""),c=StackMob.Storage.retrieve("oauth2.accessToken"),d=StackMob.Storage.retrieve("oauth2.macKey");StackMob.Storage.retrieve("oauth2.expires");if(StackMob.isOAuth2Mode()&&c&&d){var j=StackMob.METHOD_MAP[a]||"GET",e=g.split(":"),g=1<e.length?e[0]:g,h=1<e.length?e[1]:80,e=Math.round((new Date).getTime()/1E3),f="n"+Math.round(1E4*Math.random()),l=CryptoJS.HmacSHA1(e+
"\n"+f+"\n"+j+"\n"+l+"\n"+g+"\n"+h+"\n\n",d).toString(CryptoJS.enc.Base64);return'MAC id="'+c+'",ts="'+e+'",nonce="'+f+'",mac="'+l+'"'}}var f=this;_.extend(StackMob,{isSencha:function(){return f.Ext},isZepto:function(){return f.Zepto},initEnd:function(){StackMob.Model=Backbone.Model.extend({urlRoot:StackMob.urlRoot,url:function(){var a=StackMob.urlRoot||StackMob.urlError();return a+=this.schemaName},getPrimaryKeyField:function(){return this.schemaName+"_id"},constructor:function(){this.setIDAttribute();
Backbone.Model.prototype.constructor.apply(this,arguments)},initialize:function(){StackMob.getProperty(this,"schemaName")||StackMob.throwError("A schemaName must be defined");this.setIDAttribute()},setIDAttribute:function(){this.idAttribute=this.getPrimaryKeyField()},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,b,c){StackMob.sync.call(this,a,this,c)},create:function(a){var b={};b[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(b,a);this.save(null,b)},query:function(a,
b){b=b||{};_.extend(b,{query:a});this.fetch(b)},save:function(a,b){var c=a?a.success:{},l=a?a.error:{};"undefined"===typeof b&&(_.isFunction(c)||_.isFunction(l))?Backbone.Model.prototype.save.call(this,null,a):Backbone.Model.prototype.save.call(this,a,b)},fetchExpanded:function(a,b){(0>a||3<a)&&StackMob.throwError("Depth must be between 0 and 3 inclusive.");var c={};_.extend(c,b);c.data=c.data||{};c.data._expand=a;this.fetch(c)},getAsModel:function(a,b){var c=this.get(a);return c?_.isArray(c)?_.map(c,
function(a){return new b(a)}):new b(c):{}},appendAndCreate:function(a,b,c){this.addRelationship(a,b,c)},addRelationship:function(a,b,c){c=c||{};c[StackMob.ARRAY_FIELDNAME]=a;c[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"addRelationship",this,c)},appendAndSave:function(a,b,c){c=c||{};c[StackMob.ARRAY_FIELDNAME]=a;c[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"appendAndSave",this,c)},deleteAndSave:function(a,b,c,d){d=d||{};d[StackMob.ARRAY_FIELDNAME]=a;d[StackMob.ARRAY_VALUES]=b;d[StackMob.CASCADE_DELETE]=
c;var g=this;d.stackmob_ondeleteAndSave=function(){var c=g.get(a);g.set(a,_.difference(c,b))};StackMob.sync.call(this,"deleteAndSave",this,d)},setBinaryFile:function(a,b,c,d){this.set(a,"Content-Type: "+c+"\nContent-Disposition: attachment; filename="+b+"\nContent-Transfer-Encoding: base64\n\n"+d)},incrementOnSave:function(a,b){this.attributes[this.idAttribute]?(this.attributes[a]&&delete this.attributes[a],this.set(a+"[inc]",b)):StackMob.throwError("Please specify an id for the row you wish to update. When creating a new instance of your object, you need to pass in JSON that includes the id field and value (e.g. var user = new StackMob.User({ username: 'chucknorris' });)  Or, for custom objects: var todoInstance = new Todo({todo_id : '1234'})")},
decrementOnSave:function(a,b){this.incrementOnSave(a,-1*b)}});StackMob.Collection=Backbone.Collection.extend({initialize:function(){this.model||StackMob.throwError("Please specify a StackMob.Model for this collection. e.g., var Items = StackMob.Collection.extend({ model: Item });");this.schemaName=(new this.model).schemaName},url:function(){var a=StackMob.urlRoot||StackMob.urlError();return a+=this.schemaName},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,
b,c){StackMob.sync.call(this,a,this,c)},query:function(a,b){b=b||{};_.extend(b,{query:a});this.fetch(b)},create:function(a,b){var c={};c[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(c,b);Backbone.Collection.prototype.create.call(this,a,c)},count:function(a,b){a=a||new StackMob.Collection.Query;b=b||{};b.stackmob_count=!0;var c=b.success;b.success=function(a){if(a&&a.getAllResponseHeaders){var b=a.getResponseHeader("Content-Range"),d=0;b&&(d=b.substring(b.indexOf("/")+1,b.length));if(0===d)try{d=JSON.parse(a.responseText).length}catch(j){}c&&
c(d)}else c(a)};a.setRange&&(b.query=a.setRange(0,0));return(this.sync||Backbone.sync).call(this,"query",this,b)}});StackMob.User=StackMob.Model.extend({idAttribute:StackMob.loginField,schemaName:StackMob.userSchema,getPrimaryKeyField:function(){return StackMob.loginField},isLoggedIn:function(){return StackMob.isUserLoggedIn(this.get(StackMob.loginField))},login:function(a,b){b=b||{};StackMob.keepLoggedIn("undefined"===typeof a?!1:a);b.data=b.data||{};b.data[StackMob.loginField]=this.get(StackMob.loginField);
b.data[StackMob.passwordField]=this.get(StackMob.passwordField);StackMob.isOAuth2Mode()&&(b.data.token_type="mac");b.stackmob_onaccessToken=StackMob.processLogin;(this.sync||Backbone.sync).call(this,StackMob.isOAuth2Mode()?"accessToken":"login",this,b)},logout:function(a){a=a||{};a.data=a.data||{};a.stackmob_onlogout=function(){StackMob.Storage.remove(StackMob.loggedInUserKey);StackMob.Storage.remove("oauth2.accessToken");StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY);StackMob.Storage.remove("oauth2.macKey");
StackMob.Storage.remove("oauth2.expires");StackMob.Storage.remove("oauth2.user")};(this.sync||Backbone.sync).call(this,"logout",this,a)},loginWithFacebookToken:function(a,b,c){c=c||{};c.data=c.data||{};_.extend(c.data,{fb_at:a,token_type:"mac"});c.stackmob_onfacebookAccessToken=StackMob.processLogin;(this.sync||Backbone.sync).call(this,"facebookAccessToken",this,c)},createUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});b.data[StackMob.loginField]=
b[StackMob.loginField]||this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"createUserWithFacebook",this,b)},linkUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});(this.sync||Backbone.sync).call(this,"linkUserWithFacebook",this,b)},loginWithTempAndSetNewPassword:function(a,b,c,d){d=d||{};d.data=d.data||{};var g={};g[StackMob.passwordField]=a;this.set(g);d.data[StackMob.newPasswordField]=b;this.login(c,d)},forgotPassword:function(a){a=
a||{};a.data=a.data||{};a.data[StackMob.loginField]=this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"forgotPassword",this,a)},resetPassword:function(a,b,c){c=c||{};c.data=c.data||{};c.data.old={password:a};c.data["new"]={password:b};(this.sync||Backbone.sync).call(this,"resetPassword",this,c)}});StackMob.Users=StackMob.Collection.extend({model:StackMob.User});StackMob.GeoPoint=function(a,b){_.isNumber(a)?((-90>a||90<a)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),
(-180>b||180<b)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=a,this.lon=b):((-90>a.lat||90<a.lat)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),(-180>a.lon||180<a.lon)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=a.lat,this.lon=a.lon)};StackMob.GeoPoint.prototype.toJSON=function(){return{lat:this.lat,lon:this.lon}};StackMob.Model.Query=function(){this.selectFields=[];this.params=
{}};_.extend(StackMob.Model.Query.prototype,{select:function(a){this.selectFields.push(a);return this},setExpand:function(a){this.params._expand=a;return this}});StackMob.Collection.Query=function(){this.params={};this.selectFields=[];this.orderBy=[];this.range=null};StackMob.Collection.Query.prototype=new StackMob.Model.Query;StackMob.Collection.Query.prototype.constructor=StackMob.Collection.Query;_.extend(StackMob.Collection.Query.prototype,{addParam:function(a,b){this.params[a]=b;return this},
equals:function(a,b){this.params[a]=b;return this},lt:function(a,b){this.params[a+"[lt]"]=b;return this},lte:function(a,b){this.params[a+"[lte]"]=b;return this},gt:function(a,b){this.params[a+"[gt]"]=b;return this},gte:function(a,b){this.params[a+"[gte]"]=b;return this},notEquals:function(a,b){this.params[a+"[ne]"]=b;return this},isNull:function(a){this.params[a+"[null]"]=!0;return this},isNotNull:function(a){this.params[a+"[null]"]=!1;return this},mustBeOneOf:function(a,b){var c="";if(_.isArray(b))for(var d=
b.length,g=0;g<d;g++)c+=b[g],g+1<d&&(c+=",");else c=b;this.params[a+"[in]"]=c;return this},orderAsc:function(a){this.orderBy.push(a+":asc");return this},orderDesc:function(a){this.orderBy.push(a+":desc");return this},setRange:function(a,b){this.range={start:a,end:b};return this},mustBeNear:function(a,b,c){this.params[a+"[near]"]=b.lat+","+b.lon+","+c;return this},mustBeNearMi:function(a,b,c){this.mustBeNear(a,b,c/StackMob.EARTH_RADIANS_MI);return this},mustBeNearKm:function(a,b,c){this.mustBeNear(a,
b,c/StackMob.EARTH_RADIANS_KM);return this},isWithin:function(a,b,c){this.params[a+"[within]"]=b.lat+","+b.lon+","+c;return this},isWithinMi:function(a,b,c){this.isWithin(a,b,c/StackMob.EARTH_RADIANS_MI);return this},isWithinKm:function(a,b,c){this.isWithin(a,b,c/StackMob.EARTH_RADIANS_KM);return this},isWithinBox:function(a,b,c){this.params[a+"[within]"]=b.lat+","+b.lon+","+c.lat+","+c.lon;return this}})},cc:function(a,b,c,d){this.customcode(a,b,c,d)},customcode:function(a,b,c,d){_.isObject(c)?(d=
c||{},c=(c=d.httpVerb)&&!_.isUndefined(StackMob.METHOD_MAP[c.toLowerCase()])?c:"GET",d.httpVerb=c):(d=d||{},_.isString(c)&&(c&&!_.isUndefined(StackMob.METHOD_MAP[c.toLowerCase()]))&&(d.httpVerb=c.toUpperCase()));d.data=d.data||{};"GET"!==c&&(d.contentType=d.contentType||StackMob.CONTENT_TYPE_JSON);_.extend(d.data,b);d.url=this.debug?this.getDevAPIBase():this.getProdAPIBase();this.sync.call(StackMob,a,null,d)},processLogin:function(a){if(StackMob.isOAuth2Mode()){var b=a.access_token,c=a.refresh_token,
d=a.mac_key,g=a.expires_in,i=null;try{var i=a.stackmob[StackMob.userSchema][StackMob.loginField],j=StackMob.prepareCredsForSaving(b,c,d,g,i);StackMob.saveOAuthCredentials(j);StackMob.Storage.persist(StackMob.loggedInUserKey,i)}catch(e){console&&console.error("Problem saving OAuth 2.0 credentials and user")}}},getCallId:function(a,b){var c={method:a,model:b||{},time:(new Date).getTime()};return JSON.stringify(c)},sync:function(a,b,c){c=c||{};if(!StackMob.isAccessTokenMethod(a)&&StackMob.shouldSendRefreshToken()&&
!0!==c.stackmob_attempted_refresh){var l=a,g=c;g.stackmob_attempted_refresh=!0;var i=this;StackMob.refreshSession.call(StackMob,{oncomplete:function(){StackMob.sync.call(i,l,b,g)}});return!1}var j=!0===c[StackMob.FORCE_CREATE_REQUEST];j&&(a="create");var e=_.extend({type:c.httpVerb||StackMob.METHOD_MAP[a]||"GET",dataType:"json"},c);e.data=e.data||{};!e.url&&b&&(e.url=StackMob.getProperty(b,"url"));var h="cc"!=a,f=b&&b.isNew&&!b.isNew(),j=!j,p="addRelationship"==a||"appendAndSave"==a||"deleteAndSave"==
a;if(_.include("create update delete read query deleteAndSave appendAndSave addRelationship".split(" "),a)){if(p||h&&f&&j)e.url+=("/"==e.url.charAt(e.url.length-1)?"":"/")+encodeURIComponent(b.get(b.getPrimaryKeyField())),p&&(e.url+="/"+c[StackMob.ARRAY_FIELDNAME]),"deleteAndSave"==a&&(h="",h=_.isArray(c[StackMob.ARRAY_VALUES])?_.map(c[StackMob.ARRAY_VALUES],function(a){return encodeURIComponent(a)}).join(","):encodeURIComponent(c[StackMob.ARRAY_VALUES]),e.url+="/"+h)}else e.url+=("/"==e.url.charAt(e.url.length-
1)?"":"/")+a;h=c;e.headers=e.headers||{};e.headers=_.extend({Accept:"application/vnd.stackmob+json; version="+StackMob.apiVersion},e.headers);_.extend(e.headers,{"X-StackMob-User-Agent":"StackMob (JS; "+StackMob.sdkVersion+")"});StackMob.publicKey&&!StackMob.privateKey?(e.headers["X-StackMob-API-Key"]=StackMob.publicKey,e.headers["X-StackMob-Proxy-Plain"]="stackmob-api"):e.headers["X-StackMob-Proxy"]="stackmob-api";StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(a)?e.contentType="application/x-www-form-urlencoded":
_.include(["PUT","POST"],StackMob.METHOD_MAP[a])&&(e.contentType=e.contentType||StackMob.CONTENT_TYPE_JSON);isNaN(h[StackMob.CASCADE_DELETE])||(e.headers["X-StackMob-CascadeDelete"]=!0==h[StackMob.CASCADE_DELETE]);if(h.query&&(h=e.query||throwError("No StackMobQuery object provided to the query call."),h.selectFields&&0<h.selectFields.length&&(e.headers["X-StackMob-Select"]=h.selectFields.join()),h.range&&(e.headers.Range="objects="+h.range.start+"-"+h.range.end),_.extend(e.data,h.params),h.orderBy&&
0<h.orderBy.length)){h=h.orderBy;f="";j=h.length;for(p=0;p<j;p++)f+=h[p],p+1<j&&(f+=",");e.headers["X-StackMob-OrderBy"]=f}h=a;f=function(a){return _.map(_.keys(a),function(b){return b+"="+encodeURIComponent(a[b])}).join("&")};c=c||{};if(StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(h))e.data=f(e.data);else if("POST"==e.type||"PUT"==e.type)if("resetPassword"==h||"forgotPassword"==h)e.data=JSON.stringify(e.data);else if("addRelationship"==h||"appendAndSave"==h)c&&c[StackMob.ARRAY_VALUES]&&
(e.data=JSON.stringify(c[StackMob.ARRAY_VALUES]));else if(b){var k=b.toJSON();_.each(c.remote_ignore||[],function(a){delete k[a]});var q=function(a){if(a instanceof Array){if(_.reduce(a,function(a,b){return a||q(b)},!1))return!0}else return"object"==typeof a?"lat"in a&&"lon"in a?!1:!0:!1};if("true"==c.ignore_objects)for(var m in k)q(k[m])&&(console.warn("Found object in array field "+m+". Ignoring field."),delete k[m]);delete k.lastmoddate;delete k.createddate;"update"==h&&delete k[StackMob.passwordField];
StackMob.isOAuth2Mode()&&delete k.sm_owner;e.data=JSON.stringify(_.extend(k,e.data))}else e.data=JSON.stringify(e.data);else"GET"==e.type&&!_.isEmpty(e.data)&&(e.url+="?",m=f(e.data),e.url+=m),delete e.data;m=e||{};m.processData=!1;m.accepts=m.headers.Accept;StackMob.isAccessTokenMethod(a)||(m=a,StackMob.isAccessTokenMethod(m)||(m=d(m,e))&&(e.headers.Authorization=m));StackMob.makeAPICall(b,e,a)},refreshSession:function(a){var b={};_.extend(b,a);if(StackMob.hasRefreshToken()){b.url="/"+StackMob.userSchema;
b.contentType="application/x-www-form-urlencoded";b.data={refresh_token:StackMob.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY],grant_type:"refresh_token",token_type:"mac",mac_algorithm:"hmac-sha1"};var c=a.oncomplete;b.oncomplete=function(){c()};b.stackmob_onrefreshToken=StackMob.processLogin;b.error=function(){StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY)};(this.sync||Backbone.sync).call(this,"refreshToken",this,b)}},makeAPICall:function(a,b,c){return StackMob.ajax?StackMob.ajax(a,b,c):
StackMob.isSencha()?StackMob.ajaxOptions.sencha(a,b,c):StackMob.isZepto()?StackMob.ajaxOptions.zepto(a,b,c):StackMob.ajaxOptions.jquery(a,b,c)},onsuccess:function(a,b,c,d,g){if(c){if(_.isFunction(c["stackmob_on"+b]))c["stackmob_on"+b](d);if(_.isFunction(c.oncomplete))c.oncomplete(d)}g&&(d?(StackMob.isOAuth2Mode()&&(StackMob.isAccessTokenMethod(b)&&d.stackmob)&&(d=d.stackmob.user),g(d)):g())},onerror:function(a,b,c,f,g,i){var j=a.status,e;try{e=JSON.parse(b)}catch(h){e={error:"Invalid JSON returned."}}if(503==
j){a=a.getResponseHeader("retry-after");try{a=1E3*parseInt(responseHeaderValue)}catch(n){a=StackMob.RETRY_WAIT}if("number"===typeof g.stackmob_retry){if(g.stackmob_retry-=1,0>=g.stackmob_retry)return}else g.stackmob_retry=StackMob.RETRY_ATTEMPTS;_.delay(function(){var a=d(f,g);g.headers.Authorization=a;c(g)},a)}else{if(_.isFunction(g.oncomplete))g.oncomplete(e);i&&i(f,e)}},isAccessTokenMethod:function(a){return _.include(["accessToken","facebookAccessToken","refreshToken"],a)}})}).call(this);
(function(){var d=this.jQuery||this.Ext||this.Zepto;_.extend(StackMob,{ajaxOptions:{sencha:function(f,a,b){var c={},l=a.success;a.success=function(c){var d=c&&c.responseText?JSON.parse(c.responseText):null;!0===a.stackmob_count&&(d=c);StackMob.onsuccess(f,b,a,d,l)};var g=a.error;c.url=a.url;c.headers=a.headers;c.params=a.data;c.success=a.success;c.disableCaching=!1;c.method=a.type;a.error=function(a){StackMob.onerror(a,a.responseText||a.text,d.Ajax.request,f,c,g)};c.failure=a.error;return d.Ajax.request(c)},
zepto:function(f,a,b){var c=a.success,l=function(d,g){g=d?JSON.parse(d):null;StackMob.onsuccess(f,b,a,g,c)};a.success=l;var g=a.error,i=function(b){console.log("default error");StackMob.onerror(b,b.responseText||b.text,d.ajax,f,a,g)};a.error=i;var j={};j.url=a.url;j.headers=a.headers;j.contentType=a.headers.contentType;j.type=a.type;j.data=a.data;j.success=l;j.error=i;return d.ajax(j)},jquery:function(f,a,b){a.beforeSend=function(a,b){a.setRequestHeader("Accept",b.accepts);if(!_.isEmpty(b.headers))for(key in b.headers)a.setRequestHeader(key,
b.headers[key])};var c=a.error;a.error=function(b){StackMob.onerror(b,b.responseText||b.text,d.ajax,f,a,c)};var l=a.success;a.success=function(c,d,f){var e;!0===a.stackmob_count?e=f:c&&c.toJSON?e=c:c&&(c.responseText||c.text)?e=JSON.parse(c.responseText||c.text):c&&(e=c);StackMob.onsuccess(c,b,a,e,l)};return d.ajax(a)}}})}).call(this);
var CryptoJS=CryptoJS||function(d,f){var a={},b=a.lib={},c=function(){},l=b.Base={extend:function(a){c.prototype=this;var b=new c;a&&b.mixIn(a);b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.$super.extend(this)}},g=b.WordArray=l.extend({init:function(a,b){a=this.words=a||[];this.sigBytes=
b!=f?b:4*a.length},toString:function(a){return(a||j).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes,a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-8*(e%4)&255)<<24-8*((d+e)%4);else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var a=this.words,b=this.sigBytes;a[b>>>2]&=4294967295<<32-8*(b%4);a.length=d.ceil(b/4)},clone:function(){var a=l.clone.call(this);
a.words=this.words.slice(0);return a},random:function(a){for(var b=[],c=0;c<a;c+=4)b.push(4294967296*d.random()|0);return g.create(b,a)}}),i=a.enc={},j=i.Hex={stringify:function(a){for(var b=a.words,a=a.sigBytes,c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-4*(d%8);return g.create(c,b/2)}},e=i.Latin1={stringify:function(a){for(var b=
a.words,a=a.sigBytes,c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-8*(d%4);return g.create(c,b)}},h=i.Utf8={stringify:function(a){try{return decodeURIComponent(escape(e.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return e.parse(unescape(encodeURIComponent(a)))}},n=b.BufferedBlockAlgorithm=l.extend({reset:function(){this._data=g.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=h.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var b=this._data,c=b.words,e=b.sigBytes,f=this.blockSize,h=e/(4*f),h=a?d.ceil(h):d.max((h|0)-this._minBufferSize,0),a=h*f,e=d.min(4*a,e);if(a){for(var i=0;i<a;i+=f)this._doProcessBlock(c,i);i=c.splice(0,a);b.sigBytes-=e}return g.create(i,e)},clone:function(){var a=l.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});b.Hasher=n.extend({init:function(){this.reset()},
reset:function(){n.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=n.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(b,c){return a.create(c).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return p.HMAC.create(a,c).finalize(b)}}});var p=a.algo={};return a}(Math);
(function(){var d=CryptoJS,f=d.lib,a=f.WordArray,f=f.Hasher,b=[],c=d.algo.SHA1=f.extend({_doReset:function(){this._hash=a.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(a,c){for(var d=this._hash.words,f=d[0],e=d[1],h=d[2],n=d[3],p=d[4],k=0;80>k;k++){if(16>k)b[k]=a[c+k]|0;else{var q=b[k-3]^b[k-8]^b[k-14]^b[k-16];b[k]=q<<1|q>>>31}q=(f<<5|f>>>27)+p+b[k];q=20>k?q+((e&h|~e&n)+1518500249):40>k?q+((e^h^n)+1859775393):60>k?q+((e&h|e&n|h&n)-1894007588):q+((e^h^n)-
899497514);p=n;n=h;h=e<<30|e>>>2;e=f;f=q}d[0]=d[0]+f|0;d[1]=d[1]+e|0;d[2]=d[2]+h|0;d[3]=d[3]+n|0;d[4]=d[4]+p|0},_doFinalize:function(){var a=this._data,b=a.words,c=8*this._nDataBytes,d=8*a.sigBytes;b[d>>>5]|=128<<24-d%32;b[(d+64>>>9<<4)+15]=c;a.sigBytes=4*b.length;this._process()}});d.SHA1=f._createHelper(c);d.HmacSHA1=f._createHmacHelper(c)})();
(function(){var d=CryptoJS,f=d.enc.Utf8;d.algo.HMAC=d.lib.Base.extend({init:function(a,b){a=this._hasher=a.create();"string"==typeof b&&(b=f.parse(b));var c=a.blockSize,d=4*c;b.sigBytes>d&&(b=a.finalize(b));for(var g=this._oKey=b.clone(),i=this._iKey=b.clone(),j=g.words,e=i.words,h=0;h<c;h++)j[h]^=1549556828,e[h]^=909522486;g.sigBytes=i.sigBytes=d;this.reset()},reset:function(){var a=this._hasher;a.reset();a.update(this._iKey)},update:function(a){this._hasher.update(a);return this},finalize:function(a){var b=
this._hasher,a=b.finalize(a);b.reset();return b.finalize(this._oKey.clone().concat(a))}})})();
(function(){var d=CryptoJS,f=d.lib.WordArray;d.enc.Base64={stringify:function(a){var b=a.words,c=a.sigBytes,d=this._map;a.clamp();for(var a=[],f=0;f<c;f+=3)for(var i=(b[f>>>2]>>>24-8*(f%4)&255)<<16|(b[f+1>>>2]>>>24-8*((f+1)%4)&255)<<8|b[f+2>>>2]>>>24-8*((f+2)%4)&255,j=0;4>j&&f+0.75*j<c;j++)a.push(d.charAt(i>>>6*(3-j)&63));if(b=d.charAt(64))for(;a.length%4;)a.push(b);return a.join("")},parse:function(a){var a=a.replace(/\s/g,""),b=a.length,c=this._map,d=c.charAt(64);d&&(d=a.indexOf(d),-1!=d&&(b=d));
for(var d=[],g=0,i=0;i<b;i++)if(i%4){var j=c.indexOf(a.charAt(i-1))<<2*(i%4),e=c.indexOf(a.charAt(i))>>>6-2*(i%4);d[g>>>2]|=(j|e)<<24-8*(g%4);g++}return f.create(d,g)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}})();
