/*
 StackMob JS SDK Version 0.8.0 
 Copyright 2012 StackMob Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

(function(){window.StackMob=this.StackMob={DEFAULT_API_VERSION:0,DEFAULT_LOGIN_SCHEMA:"user",DEFAULT_LOGIN_FIELD:"username",DEFAULT_PASSWORD_FIELD:"password",EARTH_RADIANS_MI:3956.6,EARTH_RADIANS_KM:6367.5,FORCE_CREATE_REQUEST:"stackmob_force_create_request",ARRAY_FIELDNAME:"stackmob_array_fieldname",ARRAY_VALUES:"stackmob_array_values",CASCADE_DELETE:"stackmob_cascade_delete",HARD_DELETE:!0,SOFT_DELETE:!1,API_SERVER:"api.stackmob.com",RETRY_WAIT:1E4,RETRY_ATTEMPTS:3,REFRESH_TOKEN_KEY:"oauth2.refreshToken",
POST:"POST",PUT:"PUT",DELETE:"DELETE",CONTENT_TYPE_JSON:"application/json",apiVersion:0,sdkVersion:"0.8.0",publicKey:null,Storage:{STORAGE_PREFIX:"stackmob.",persist:function(c,f){localStorage&&localStorage.setItem(this.STORAGE_PREFIX+c,f)},retrieve:function(c){return localStorage?localStorage.getItem(this.STORAGE_PREFIX+c):null},remove:function(c){localStorage&&localStorage.removeItem(this.STORAGE_PREFIX+c)}},_generateCallbacks:function(c,f){c.success=function(a){f.isValidResult(a)?"function"===
typeof f.yes&&f.yes(a):"function"===typeof f.no&&f.no(a)};!c.error&&"function"===typeof f.error&&(c.error=f.error);return c},_containsCallbacks:function(c,f){return"object"===typeof c&&_.some(f,function(a){return"function"===typeof c[a]})},getLoggedInUser:function(c){var f=!this.isOAuth2Mode()&&this.Storage.retrieve(this.loggedInUserKey)||this.Storage.retrieve("oauth2.user");if(c&&c.success)this.hasValidOAuth(c);else return this.isLoggedIn(c)&&f?f:null},isLoggedIn:function(c){if(this._containsCallbacks(c,
["yes","no"]))c=this._generateCallbacks(c,{isValidResult:function(c){return"undefined"!==typeof c},yes:c.yes,no:c.no,error:c.no}),this.hasValidOAuth(c);else return!this.isLoggedOut()||this.hasValidOAuth(c)},isUserLoggedIn:function(c,f){if(this._containsCallbacks(f,["yes","no"]))f=this._generateCallbacks(f,{isValidResult:function(a){return a==c},yes:f.yes,no:f.no,error:f.no}),this.hasValidOAuth(f);else return c==this.getLoggedInUser(f)},isLoggedOut:function(c){if(this._containsCallbacks(c,["yes","no"]))c=
this._generateCallbacks(c,{isValidResult:function(c){return"undefined"==typeof c},yes:c.yes,no:c.no,error:c.yes}),this.hasValidOAuth(c);else return!this.hasValidOAuth(c)},getScheme:function(){return!0===this.secure?"https":"http"},getBaseURL:function(){return StackMob.useRelativePathForAjax?StackMob.apiURL||window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:"")+"/":StackMob.apiURL||this.getScheme()+"://"+StackMob.API_SERVER+"/"},throwError:function(c){throw Error(c);
},urlError:function(){this.throwError('A "url" property or function must be specified')},requirePublicKey:function(){StackMob.publicKey||this.throwError("Error: This requires that you initialize StackMob with a public key.")},isOAuth2Mode:function(){return!isNaN(StackMob.publicKey&&!StackMob.privateKey)},prepareCredsForSaving:function(c,f,a,b,d){b=(new Date).getTime()+1E3*b;c={"oauth2.accessToken":c,"oauth2.macKey":a,"oauth2.expires":b,"oauth2.user":d};c[StackMob.REFRESH_TOKEN_KEY]=f;return c},saveOAuthCredentials:function(c){var f=
c["oauth2.accessToken"],a=c[StackMob.REFRESH_TOKEN_KEY];this.Storage.retrieve("oauth2.accessToken")!=f&&this.Storage.persist("oauth2.expires",c["oauth2.expires"]);this.Storage.persist("oauth2.accessToken",f);this.Storage.persist(StackMob.REFRESH_TOKEN_KEY,a);this.Storage.persist("oauth2.macKey",c["oauth2.macKey"]);this.Storage.persist("oauth2.user",c["oauth2.user"])},hasValidOAuth:function(c){if(!this.isOAuth2Mode())return c&&c.error&&c.error(),!1;var f=this.getOAuthCredentials();if(!_.all([f["oauth2.accessToken"],
f["oauth2.macKey"],f["oauth2.expires"]||0],_.identity))return c&&c.success&&c.success(void 0),!1;if(StackMob.hasExpiredOAuth())if(c&&c.success){var a=c.success;c.success=function(b){a(b[StackMob.loginField])};StackMob.refreshSession.call(StackMob,c)}else return!1;else return c&&c.success&&c.success(this.Storage.retrieve("oauth2.user")),this.Storage.retrieve("oauth2.user")},shouldSendRefreshToken:function(){return this.hasExpiredOAuth()&&this.hasRefreshToken()&&this.shouldKeepLoggedIn()},keepLoggedIn:function(c){StackMob.Storage.persist("oauth2.shouldKeepLoggedIn",
!0===c)},shouldKeepLoggedIn:function(){return"true"===StackMob.Storage.retrieve("oauth2.shouldKeepLoggedIn")},hasRefreshToken:function(){var c=this.getOAuthCredentials();return c&&"undefined"!==typeof c[StackMob.REFRESH_TOKEN_KEY]&&null!=c[StackMob.REFRESH_TOKEN_KEY]},getRefreshToken:function(){return this.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY]},hasExpiredOAuth:function(){return this.isOAuth2Mode()&&null==this.getOAuthExpireTime()||this.getOAuthExpireTime()<=(new Date).getTime()},getOAuthCredentials:function(){var c=
StackMob.Storage.retrieve("oauth2.accessToken"),f=StackMob.Storage.retrieve("oauth2.macKey"),a=StackMob.Storage.retrieve("oauth2.expires"),b=StackMob.Storage.retrieve(StackMob.REFRESH_TOKEN_KEY),c={"oauth2.accessToken":c,"oauth2.macKey":f,"oauth2.expires":a};c[StackMob.REFRESH_TOKEN_KEY]=b;return c},getOAuthExpireTime:function(){var c=this.Storage.retrieve("oauth2.expires");return c?parseInt(c):null},METHOD_MAP:{create:"POST",read:"GET",update:"PUT","delete":"DELETE",post:"POST",get:"GET",put:"PUT",
addRelationship:"POST",appendAndSave:"PUT",deleteAndSave:"DELETE",login:"GET",accessToken:"POST",refreshToken:"POST",logout:"GET",forgotPassword:"POST",loginWithTempAndSetNewPassword:"GET",resetPassword:"POST",facebookAccessToken:"POST",createUserWithFacebook:"POST",linkUserWithFacebook:"POST"},getProperty:function(c,f){return!c||!c[f]?null:_.isFunction(c[f])?c[f]():c[f]},init:function(c){c=c||{};this.initStart(c);this.userSchema=c.userSchema||this.DEFAULT_LOGIN_SCHEMA;this.loginField=c.loginField||
this.DEFAULT_LOGIN_FIELD;this.passwordField=c.passwordField||this.DEFAULT_PASSWORD_FIELD;this.newPasswordField=c.newPasswordField||"new_password";this.apiVersion=c.apiVersion||this.DEFAULT_API_VERSION;this.appName=this.getProperty(c,"appName")||this.throwError("An appName must be specified");this.clientSubdomain=this.getProperty(c,"clientSubdomain");this.publicKey=c.publicKey;this.apiURL=c.apiURL;var f=0<window.location.hostname.indexOf(".stackmobapp.com");this.useRelativePathForAjax=c.useRelativePathForAjax||
f;this.oauth2targetdomain=c.oauth2targetdomain||this.oauth2targetdomain||"www.stackmob.com";this.secure=!0===c.secure;this.fullURL=!0===c.fullURL||"undefined"!==typeof PhoneGap||this.fullURL;this.ajax=c.ajax||this.ajax;this.urlRoot=c.urlRoot||this.getBaseURL();this.initEnd(c);return this},initStart:function(){},initEnd:function(){}}}).call(this);
(function(){function c(a,b){var d=StackMob.getBaseURL(),c=b.url.replace(RegExp(d,"g"),"/"),g=d.replace(RegExp("^http://|^https://","g"),"").replace(/\//,""),i=StackMob.Storage.retrieve("oauth2.accessToken"),f=StackMob.Storage.retrieve("oauth2.macKey");StackMob.Storage.retrieve("oauth2.expires");if(StackMob.isOAuth2Mode()&&i&&f){var e=b.type,h=g.split(":"),g=1<h.length?h[0]:g,k=1<h.length?h[1]:"https"==d.substring(0,5)?443:80,d=Math.round((new Date).getTime()/1E3),h="n"+Math.round(1E4*Math.random()),
c=CryptoJS.HmacSHA1(d+"\n"+h+"\n"+e+"\n"+c+"\n"+g+"\n"+k+"\n\n",f).toString(CryptoJS.enc.Base64);return'MAC id="'+i+'",ts="'+d+'",nonce="'+h+'",mac="'+c+'"'}}var f=this;_.extend(StackMob,{isSencha:function(){return f.Ext},isZepto:function(){return f.Zepto},initEnd:function(){StackMob.Model=Backbone.Model.extend({urlRoot:StackMob.urlRoot,url:function(){var a=StackMob.urlRoot||StackMob.urlError();return a+=this.schemaName},getPrimaryKeyField:function(){return this.schemaName+"_id"},constructor:function(){this.setIDAttribute();
Backbone.Model.prototype.constructor.apply(this,arguments)},initialize:function(){StackMob.getProperty(this,"schemaName")||StackMob.throwError("A schemaName must be defined");this.setIDAttribute()},setIDAttribute:function(){this.idAttribute=this.getPrimaryKeyField()},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,b,d){StackMob.sync.call(this,a,this,d)},create:function(a){var b={};b[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(b,a);this.save(null,b)},query:function(a,
b){b=b||{};_.extend(b,{query:a});this.fetch(b)},save:function(a,b){var d=a?a.success:{},c=a?a.error:{};"undefined"===typeof b&&(_.isFunction(d)||_.isFunction(c))?Backbone.Model.prototype.save.call(this,null,a):Backbone.Model.prototype.save.call(this,a,b)},fetchExpanded:function(a,b){(0>a||3<a)&&StackMob.throwError("Depth must be between 0 and 3 inclusive.");var d={};_.extend(d,b);d.data=d.data||{};d.data._expand=a;this.fetch(d)},getAsModel:function(a,b){var d=this.get(a);return d?_.isArray(d)?_.map(d,
function(a){return new b(a)}):new b(d):{}},appendAndCreate:function(a,b,d){this.addRelationship(a,b,d)},addRelationship:function(a,b,d){d=d||{};d[StackMob.ARRAY_FIELDNAME]=a;d[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"addRelationship",this,d)},appendAndSave:function(a,b,d){d=d||{};d[StackMob.ARRAY_FIELDNAME]=a;d[StackMob.ARRAY_VALUES]=b;StackMob.sync.call(this,"appendAndSave",this,d)},deleteAndSave:function(a,b,d,c){c=c||{};c[StackMob.ARRAY_FIELDNAME]=a;c[StackMob.ARRAY_VALUES]=b;c[StackMob.CASCADE_DELETE]=
d;var g=this;c.stackmob_ondeleteAndSave=function(){var d=g.get(a);g.set(a,_.difference(d,b))};StackMob.sync.call(this,"deleteAndSave",this,c)},setBinaryFile:function(a,b,d,c){this.set(a,"Content-Type: "+d+"\nContent-Disposition: attachment; filename="+b+"\nContent-Transfer-Encoding: base64\n\n"+c)},incrementOnSave:function(a,b){this.attributes[this.idAttribute]?(this.attributes[a]&&delete this.attributes[a],this.set(a+"[inc]",b)):StackMob.throwError("Please specify an id for the row you wish to update. When creating a new instance of your object, you need to pass in JSON that includes the id field and value (e.g. var user = new StackMob.User({ username: 'chucknorris' });)  Or, for custom objects: var todoInstance = new Todo({todo_id : '1234'})")},
decrementOnSave:function(a,b){this.incrementOnSave(a,-1*b)}});StackMob.Collection=Backbone.Collection.extend({initialize:function(){this.model||StackMob.throwError("Please specify a StackMob.Model for this collection. e.g., var Items = StackMob.Collection.extend({ model: Item });");this.schemaName=(new this.model).schemaName},url:function(){var a=StackMob.urlRoot||StackMob.urlError();return a+=this.schemaName},parse:function(a){return!a||a&&(!a.text||""==a.text)?a:JSON.parse(a.text)},sync:function(a,
b,d){StackMob.sync.call(this,a,this,d)},query:function(a,b){b=b||{};_.extend(b,{query:a});this.fetch(b)},create:function(a,b){var d={};d[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(d,b);Backbone.Collection.prototype.create.call(this,a,d)},count:function(a,b){a=a||new StackMob.Collection.Query;b=b||{};b.stackmob_count=!0;var d=b.success;b.success=function(a){if(a&&a.getAllResponseHeaders){var b=a.getResponseHeader("Content-Range"),c=0;b&&(c=b.substring(b.indexOf("/")+1,b.length));if(0===c)try{c=JSON.parse(a.responseText).length}catch(f){}d&&
d(c)}else d(a)};a.setRange&&(b.query=a.setRange(0,0));return(this.sync||Backbone.sync).call(this,"query",this,b)}});StackMob.User=StackMob.Model.extend({idAttribute:StackMob.loginField,schemaName:StackMob.userSchema,getPrimaryKeyField:function(){return StackMob.loginField},isLoggedIn:function(a){if(StackMob._containsCallbacks(a,["yes","no"]))a=StackMob._generateCallbacks(a,{isValidResult:function(a){return"undefined"!==typeof a},yes:a.yes,no:a.no,error:a.no}),StackMob.hasValidOAuth(a);else return StackMob.isUserLoggedIn(this.get(StackMob.loginField),
a)},login:function(a,b){b=b||{};StackMob.keepLoggedIn("undefined"===typeof a?!1:a);b.data=b.data||{};b.data[StackMob.loginField]=this.get(StackMob.loginField);b.data[StackMob.passwordField]=this.get(StackMob.passwordField);StackMob.isOAuth2Mode()&&(b.data.token_type="mac");b.stackmob_onaccessToken=StackMob.processLogin;(this.sync||Backbone.sync).call(this,StackMob.isOAuth2Mode()?"accessToken":"login",this,b)},logout:function(a){a=a||{};a.data=a.data||{};a.stackmob_onlogout=function(){StackMob.Storage.remove(StackMob.loggedInUserKey);
StackMob.Storage.remove("oauth2.accessToken");StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY);StackMob.Storage.remove("oauth2.macKey");StackMob.Storage.remove("oauth2.expires");StackMob.Storage.remove("oauth2.user")};(this.sync||Backbone.sync).call(this,"logout",this,a)},loginWithFacebookToken:function(a,b,d){d=d||{};d.data=d.data||{};_.extend(d.data,{fb_at:a,token_type:"mac"});d.stackmob_onfacebookAccessToken=StackMob.processLogin;(this.sync||Backbone.sync).call(this,"facebookAccessToken",this,
d)},createUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});b.data[StackMob.loginField]=b[StackMob.loginField]||this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"createUserWithFacebook",this,b)},linkUserWithFacebook:function(a,b){b=b||{};b.data=b.data||{};_.extend(b.data,{fb_at:a,token_type:"mac"});(this.sync||Backbone.sync).call(this,"linkUserWithFacebook",this,b)},loginWithTempAndSetNewPassword:function(a,b,d,c){c=c||{};c.data=
c.data||{};var g={};g[StackMob.passwordField]=a;this.set(g);c.data[StackMob.newPasswordField]=b;this.login(d,c)},forgotPassword:function(a){a=a||{};a.data=a.data||{};a.data[StackMob.loginField]=this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"forgotPassword",this,a)},resetPassword:function(a,b,d){d=d||{};d.data=d.data||{};d.data.old={password:a};d.data["new"]={password:b};(this.sync||Backbone.sync).call(this,"resetPassword",this,d)}});StackMob.Users=StackMob.Collection.extend({model:StackMob.User});
StackMob.GeoPoint=function(a,b){_.isNumber(a)?((-90>a||90<a)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),(-180>b||180<b)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=a,this.lon=b):((-90>a.lat||90<a.lat)&&StackMob.throwError("Latitude value must be between -90 and 90 inclusive."),(-180>a.lon||180<a.lon)&&StackMob.throwError("Longitude value must be between -180 and 180 inclusive."),this.lat=a.lat,this.lon=a.lon)};StackMob.GeoPoint.prototype.toJSON=
function(){return{lat:this.lat,lon:this.lon}};StackMob.Model.Query=function(){this.selectFields=[];this.params={}};_.extend(StackMob.Model.Query.prototype,{select:function(a){this.selectFields.push(a);return this},setExpand:function(a){this.params._expand=a;return this}});StackMob.Collection.Query=function(){this.params={};this.selectFields=[];this.orderBy=[];this.range=null};StackMob.Collection.Query.prototype=new StackMob.Model.Query;StackMob.Collection.Query.prototype.constructor=StackMob.Collection.Query;
_.extend(StackMob.Collection.Query.prototype,{addParam:function(a,b){this.params[a]=b;return this},equals:function(a,b){this.params[a]=b;return this},lt:function(a,b){this.params[a+"[lt]"]=b;return this},lte:function(a,b){this.params[a+"[lte]"]=b;return this},gt:function(a,b){this.params[a+"[gt]"]=b;return this},gte:function(a,b){this.params[a+"[gte]"]=b;return this},notEquals:function(a,b){this.params[a+"[ne]"]=b;return this},isNull:function(a){this.params[a+"[null]"]=!0;return this},isNotNull:function(a){this.params[a+
"[null]"]=!1;return this},mustBeOneOf:function(a,b){var d="";if(_.isArray(b))for(var c=b.length,g=0;g<c;g++)d+=b[g],g+1<c&&(d+=",");else d=b;this.params[a+"[in]"]=d;return this},orderAsc:function(a){this.orderBy.push(a+":asc");return this},orderDesc:function(a){this.orderBy.push(a+":desc");return this},setRange:function(a,b){this.range={start:a,end:b};return this},mustBeNear:function(a,b,d){this.params[a+"[near]"]=b.lat+","+b.lon+","+d;return this},mustBeNearMi:function(a,b,d){this.mustBeNear(a,b,
d/StackMob.EARTH_RADIANS_MI);return this},mustBeNearKm:function(a,b,d){this.mustBeNear(a,b,d/StackMob.EARTH_RADIANS_KM);return this},isWithin:function(a,b,d){this.params[a+"[within]"]=b.lat+","+b.lon+","+d;return this},isWithinMi:function(a,b,d){this.isWithin(a,b,d/StackMob.EARTH_RADIANS_MI);return this},isWithinKm:function(a,b,d){this.isWithin(a,b,d/StackMob.EARTH_RADIANS_KM);return this},isWithinBox:function(a,b,d){this.params[a+"[within]"]=b.lat+","+b.lon+","+d.lat+","+d.lon;return this}})},cc:function(a,
b,d,c){this.customcode(a,b,d,c)},customcode:function(a,b,d,c){_.isObject(d)?(c=d||{},d=(d=c.httpVerb)&&!_.isUndefined(StackMob.METHOD_MAP[d.toLowerCase()])?d:"GET",c.httpVerb=d):(c=c||{},_.isString(d)&&(d&&!_.isUndefined(StackMob.METHOD_MAP[d.toLowerCase()]))&&(c.httpVerb=d.toUpperCase()));c.data=c.data||{};"GET"!==d&&(c.contentType=c.contentType||StackMob.CONTENT_TYPE_JSON);_.extend(c.data,b);c.url=this.getBaseURL();this.sync.call(StackMob,a,null,c)},processLogin:function(a){if(StackMob.isOAuth2Mode()){var b=
a.access_token,d=a.refresh_token,c=a.mac_key,g=a.expires_in,f=null;try{var f=a.stackmob.user[StackMob.loginField],j=StackMob.prepareCredsForSaving(b,d,c,g,f);StackMob.saveOAuthCredentials(j);StackMob.Storage.persist(StackMob.loggedInUserKey,f)}catch(e){console&&console.error("Problem saving OAuth 2.0 credentials and user")}}},getCallId:function(a,b){var c={method:a,model:b||{},time:(new Date).getTime()};return JSON.stringify(c)},sync:function(a,b,d){d=d||{};if(!StackMob.isAccessTokenMethod(a)&&StackMob.shouldSendRefreshToken()&&
!0!==d.stackmob_attempted_refresh){var f=a,g=d;g.stackmob_attempted_refresh=!0;var i=this;StackMob.refreshSession.call(StackMob,{oncomplete:function(){StackMob.sync.call(i,f,b,g)}});return!1}var j=!0===d[StackMob.FORCE_CREATE_REQUEST];j&&(a="create");var e=_.extend({type:d.httpVerb||StackMob.METHOD_MAP[a]||"GET",dataType:"json"},d);e.data=e.data||{};!e.url&&b&&(e.url=StackMob.getProperty(b,"url"));var h="cc"!=a,k=b&&b.isNew&&!b.isNew(),j=!j,n="addRelationship"==a||"appendAndSave"==a||"deleteAndSave"==
a;if(_.include("create update delete read query deleteAndSave appendAndSave addRelationship".split(" "),a)){if(n||h&&k&&j)e.url+=("/"==e.url.charAt(e.url.length-1)?"":"/")+encodeURIComponent(b.get(b.getPrimaryKeyField())),n&&(e.url+="/"+d[StackMob.ARRAY_FIELDNAME]),"deleteAndSave"==a&&(h="",h=_.isArray(d[StackMob.ARRAY_VALUES])?_.map(d[StackMob.ARRAY_VALUES],function(a){return encodeURIComponent(a)}).join(","):encodeURIComponent(d[StackMob.ARRAY_VALUES]),e.url+="/"+h)}else e.url+=("/"==e.url.charAt(e.url.length-
1)?"":"/")+a;h=d;e.headers=e.headers||{};e.headers=_.extend({Accept:"application/vnd.stackmob+json; version="+StackMob.apiVersion},e.headers);_.extend(e.headers,{"X-StackMob-User-Agent":"StackMob (JS; "+StackMob.sdkVersion+")"});StackMob.publicKey&&!StackMob.privateKey?(e.headers["X-StackMob-API-Key"]=StackMob.publicKey,e.headers["X-StackMob-Proxy-Plain"]="stackmob-api",e.headers["X-StackMob-API-Key-"+StackMob.publicKey]=""):e.headers["X-StackMob-Proxy"]="stackmob-api";StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(a)?
e.contentType="application/x-www-form-urlencoded":_.include(["PUT","POST"],StackMob.METHOD_MAP[a])&&(e.contentType=e.contentType||StackMob.CONTENT_TYPE_JSON);isNaN(h[StackMob.CASCADE_DELETE])||(e.headers["X-StackMob-CascadeDelete"]=!0==h[StackMob.CASCADE_DELETE]);if(h.query&&(h=e.query||throwError("No StackMobQuery object provided to the query call."),h.selectFields&&0<h.selectFields.length&&(e.headers["X-StackMob-Select"]=h.selectFields.join()),h.range&&(e.headers.Range="objects="+h.range.start+
"-"+h.range.end),_.extend(e.data,h.params),h.orderBy&&0<h.orderBy.length)){h=h.orderBy;k="";j=h.length;for(n=0;n<j;n++)k+=h[n],n+1<j&&(k+=",");e.headers["X-StackMob-OrderBy"]=k}h=a;k=function(a){return _.map(_.keys(a),function(b){return b+"="+encodeURIComponent(a[b])}).join("&")};d=d||{};if(StackMob.isOAuth2Mode()&&StackMob.isAccessTokenMethod(h))e.data=k(e.data);else if("POST"==e.type||"PUT"==e.type)if("resetPassword"==h||"forgotPassword"==h)e.data=JSON.stringify(e.data);else if("addRelationship"==
h||"appendAndSave"==h)d&&d[StackMob.ARRAY_VALUES]&&(e.data=JSON.stringify(d[StackMob.ARRAY_VALUES]));else if(b){var m=b.toJSON();_.each(d.remote_ignore||[],function(a){delete m[a]});delete m.lastmoddate;delete m.createddate;"update"==h&&delete m[StackMob.passwordField];StackMob.isOAuth2Mode()&&delete m.sm_owner;e.data=JSON.stringify(_.extend(m,e.data))}else e.data=JSON.stringify(e.data);else"GET"==e.type&&!_.isEmpty(e.data)&&(e.url+="?",d=k(e.data),e.url+=d),delete e.data;d=e||{};d.processData=!1;
d.accepts=d.headers.Accept;StackMob.isAccessTokenMethod(a)||(d=a,StackMob.isAccessTokenMethod(d)||(d=c(d,e))&&(e.headers.Authorization=d));StackMob.makeAPICall(b,e,a)},refreshSession:function(a){var b={};_.extend(b,a);if(StackMob.hasRefreshToken()){b.url="/"+StackMob.userSchema;b.contentType="application/x-www-form-urlencoded";b.data={refresh_token:StackMob.getOAuthCredentials()[StackMob.REFRESH_TOKEN_KEY],grant_type:"refresh_token",token_type:"mac",mac_algorithm:"hmac-sha1"};var c=a.oncomplete;c&&
(b.oncomplete=function(){c()});a&&a.success&&(b.success=a.success);b.stackmob_onrefreshToken=StackMob.processLogin;b.error=function(){a&&a.error&&a.error();StackMob.Storage.remove(StackMob.REFRESH_TOKEN_KEY)};(this.sync||Backbone.sync).call(this,"refreshToken",this,b)}else a&&a.error&&a.error()},makeAPICall:function(a,b,c){return StackMob.ajax?StackMob.ajax(a,b,c):StackMob.isSencha()?StackMob.ajaxOptions.sencha(a,b,c):StackMob.isZepto()?StackMob.ajaxOptions.zepto(a,b,c):StackMob.ajaxOptions.jquery(a,
b,c)},onsuccess:function(a,b,c,f,g){if(c){if(_.isFunction(c["stackmob_on"+b]))c["stackmob_on"+b](f);if(_.isFunction(c.oncomplete))c.oncomplete(f)}g&&(f?(StackMob.isOAuth2Mode()&&(StackMob.isAccessTokenMethod(b)&&f.stackmob)&&(f=f.stackmob.user),g(f)):g())},onerror:function(a,b,d,f,g,i){var j=a.status,e;try{e=JSON.parse(b)}catch(h){e={error:"Invalid JSON returned."}}if(503==j){a=a.getResponseHeader("retry-after");try{a=1E3*parseInt(responseHeaderValue)}catch(k){a=StackMob.RETRY_WAIT}if("number"===
typeof g.stackmob_retry){if(g.stackmob_retry-=1,0>=g.stackmob_retry)return}else g.stackmob_retry=StackMob.RETRY_ATTEMPTS;_.delay(function(){var a=c(f,g);g.headers.Authorization=a;d(g)},a)}else{if(_.isFunction(g.oncomplete))g.oncomplete(e);i&&i(f,e)}},isAccessTokenMethod:function(a){return _.include(["accessToken","facebookAccessToken","refreshToken"],a)}})}).call(this);
(function(){var c=this.jQuery||this.Ext||this.Zepto;_.extend(StackMob,{ajaxOptions:{sencha:function(f,a,b){var d={},l=a.success;a.success=function(c){var d=c&&c.responseText?JSON.parse(c.responseText):null;!0===a.stackmob_count&&(d=c);StackMob.onsuccess(f,b,a,d,l)};var g=a.error;d.url=a.url;d.headers=a.headers;d.params=a.data;d.success=a.success;d.disableCaching=!1;d.method=a.type;a.error=function(a){StackMob.onerror(a,a.responseText||a.text,c.Ajax.request,f,d,g)};d.failure=a.error;return c.Ajax.request(d)},
zepto:function(f,a,b){var d=a.success,l=function(c,g){g=c?JSON.parse(c):null;StackMob.onsuccess(f,b,a,g,d)};a.success=l;var g=a.error,i=function(b){StackMob.onerror(b,b.responseText||b.text,c.ajax,f,a,g)};a.error=i;var j={};j.url=a.url;j.headers=a.headers;j.contentType=a.headers.contentType;j.type=a.type;j.data=a.data;j.success=l;j.error=i;return c.ajax(j)},jquery:function(f,a,b){a.beforeSend=function(a,b){a.setRequestHeader("Accept",b.accepts);if(!_.isEmpty(b.headers))for(key in b.headers)a.setRequestHeader(key,
b.headers[key])};var d=a.error;a.error=function(b,i,j){if(0==b.status&&a.query&&"object"===typeof a.query.range)this.success(b,i,j);else StackMob.onerror(b,b.responseText||b.text,c.ajax,f,a,d)};var l=a.success;a.success=function(c,d,f){var e;!0===a.stackmob_count?e=f:c&&c.toJSON?e=c:c&&(c.responseText||c.text)?e=JSON.parse(c.responseText||c.text):c&&(e=c);StackMob.onsuccess(c,b,a,e,l)};return c.ajax(a)}}})}).call(this);
var CryptoJS=CryptoJS||function(c,f){var a={},b=a.lib={},d=function(){},l=b.Base={extend:function(a){d.prototype=this;var b=new d;a&&b.mixIn(a);b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.$super.extend(this)}},g=b.WordArray=l.extend({init:function(a,b){a=this.words=a||[];this.sigBytes=
b!=f?b:4*a.length},toString:function(a){return(a||j).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes,a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-8*(e%4)&255)<<24-8*((d+e)%4);else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var a=this.words,b=this.sigBytes;a[b>>>2]&=4294967295<<32-8*(b%4);a.length=c.ceil(b/4)},clone:function(){var a=l.clone.call(this);
a.words=this.words.slice(0);return a},random:function(a){for(var b=[],d=0;d<a;d+=4)b.push(4294967296*c.random()|0);return g.create(b,a)}}),i=a.enc={},j=i.Hex={stringify:function(a){for(var b=a.words,a=a.sigBytes,c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-8*(d%4)&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-4*(d%8);return g.create(c,b/2)}},e=i.Latin1={stringify:function(a){for(var b=
a.words,a=a.sigBytes,c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-8*(d%4)&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-8*(d%4);return g.create(c,b)}},h=i.Utf8={stringify:function(a){try{return decodeURIComponent(escape(e.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return e.parse(unescape(encodeURIComponent(a)))}},k=b.BufferedBlockAlgorithm=l.extend({reset:function(){this._data=g.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=h.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var b=this._data,d=b.words,e=b.sigBytes,f=this.blockSize,h=e/(4*f),h=a?c.ceil(h):c.max((h|0)-this._minBufferSize,0),a=h*f,e=c.min(4*a,e);if(a){for(var i=0;i<a;i+=f)this._doProcessBlock(d,i);i=d.splice(0,a);b.sigBytes-=e}return g.create(i,e)},clone:function(){var a=l.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});b.Hasher=k.extend({init:function(){this.reset()},
reset:function(){k.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=k.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(b,c){return a.create(c).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return n.HMAC.create(a,c).finalize(b)}}});var n=a.algo={};return a}(Math);
(function(){var c=CryptoJS,f=c.lib,a=f.WordArray,f=f.Hasher,b=[],d=c.algo.SHA1=f.extend({_doReset:function(){this._hash=a.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(a,c){for(var d=this._hash.words,f=d[0],e=d[1],h=d[2],k=d[3],n=d[4],m=0;80>m;m++){if(16>m)b[m]=a[c+m]|0;else{var p=b[m-3]^b[m-8]^b[m-14]^b[m-16];b[m]=p<<1|p>>>31}p=(f<<5|f>>>27)+n+b[m];p=20>m?p+((e&h|~e&k)+1518500249):40>m?p+((e^h^k)+1859775393):60>m?p+((e&h|e&k|h&k)-1894007588):p+((e^h^k)-
899497514);n=k;k=h;h=e<<30|e>>>2;e=f;f=p}d[0]=d[0]+f|0;d[1]=d[1]+e|0;d[2]=d[2]+h|0;d[3]=d[3]+k|0;d[4]=d[4]+n|0},_doFinalize:function(){var a=this._data,b=a.words,c=8*this._nDataBytes,d=8*a.sigBytes;b[d>>>5]|=128<<24-d%32;b[(d+64>>>9<<4)+15]=c;a.sigBytes=4*b.length;this._process()}});c.SHA1=f._createHelper(d);c.HmacSHA1=f._createHmacHelper(d)})();
(function(){var c=CryptoJS,f=c.enc.Utf8;c.algo.HMAC=c.lib.Base.extend({init:function(a,b){a=this._hasher=a.create();"string"==typeof b&&(b=f.parse(b));var c=a.blockSize,l=4*c;b.sigBytes>l&&(b=a.finalize(b));for(var g=this._oKey=b.clone(),i=this._iKey=b.clone(),j=g.words,e=i.words,h=0;h<c;h++)j[h]^=1549556828,e[h]^=909522486;g.sigBytes=i.sigBytes=l;this.reset()},reset:function(){var a=this._hasher;a.reset();a.update(this._iKey)},update:function(a){this._hasher.update(a);return this},finalize:function(a){var b=
this._hasher,a=b.finalize(a);b.reset();return b.finalize(this._oKey.clone().concat(a))}})})();
(function(){var c=CryptoJS,f=c.lib.WordArray;c.enc.Base64={stringify:function(a){var b=a.words,c=a.sigBytes,f=this._map;a.clamp();for(var a=[],g=0;g<c;g+=3)for(var i=(b[g>>>2]>>>24-8*(g%4)&255)<<16|(b[g+1>>>2]>>>24-8*((g+1)%4)&255)<<8|b[g+2>>>2]>>>24-8*((g+2)%4)&255,j=0;4>j&&g+0.75*j<c;j++)a.push(f.charAt(i>>>6*(3-j)&63));if(b=f.charAt(64))for(;a.length%4;)a.push(b);return a.join("")},parse:function(a){var a=a.replace(/\s/g,""),b=a.length,c=this._map,l=c.charAt(64);l&&(l=a.indexOf(l),-1!=l&&(b=l));
for(var l=[],g=0,i=0;i<b;i++)if(i%4){var j=c.indexOf(a.charAt(i-1))<<2*(i%4),e=c.indexOf(a.charAt(i))>>>6-2*(i%4);l[g>>>2]|=(j|e)<<24-8*(g%4);g++}return f.create(l,g)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}})();
